version: "2"
services:
  stowage:
    build: .
    container_name: stowage
    ports:
      - "8084:8084"
    depends_on:
      - mongo 
  mongo:
    image: mongo
    container_name: mongo
    volumes:
        - ./data:/data/db
    ports:
      - "27017:27017"