version: "2"
services:
  stowage:
    build: .
    image: stowage
    container_name: stowage
    volumes:
      - ./resources:/resources
    ports:
      - "80:80"
    depends_on:
      - mongo 
  mongo:
    image: mongo
    container_name: mongo
    volumes:
        - ./data:/data/db
    ports:
      - "27017:27017"