version: "2"
services:
  atmosphere:
    image: atmosphereframework/atmosphere-api:latest
    ports:
      - "8084:8084"
    depends_on:
      - mongo 
  mongo:
    image: mongo
    volumes:
        - ./data:/data/db
    ports:
      - "27017:27017"